gcodeproj/gcodedb/urls.py
from django.urls import path,include
from . import views,importxls,exportxls
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from django import views as myapp_views

app_name = "gcodedb"

urlpatterns = [
    path('offer/insert/', views.offer_form,name='offer_insert'),
    path('offer/', importxls.importxls_offer,name='importxls_offer'),
    path('offer/update/<int:id>/', views.offer_form,name='offer_update'), 
    path('offer/delete/<int:id>/',views.offer_delete,name='offer_delete'),
    path('offer/export/xls', exportxls.exportxls_offer, name='exportxls_offer'),

    path('nlb/insert/', views.nlb_form,name='nlb_insert'),
    path('nlb/', importxls.importxls_nlb,name='importxls_nlb'),
    path('nlb/update/<int:id>/', views.nlb_form,name='nlb_update'), 
    path('nlb/delete/<int:id>/',views.nlb_delete,name='nlb_delete'),
    path('nlb/export/xls/', exportxls.exportxls_nlb, name='exportxls_nlb'),

    path('nlm/insert/', views.nlm_form,name='nlm_insert'),
    path('nlm/', views.nlm_list,name='nlm_list'),
    path('nlm/update/<int:id>/', views.nlm_form,name='nlm_update'), 
    path('nlm/delete/<int:id>/',views.nlm_delete,name='nlm_delete'),
    path('nlm/import/xls', importxls.importxls_nlm, name='importxls_nlm'),
    path('nlm/export/xls/<int:contractid>', exportxls.exportxls_nlm, name='exportxls_nlm'),

    path('phat/insert/', views.phat_form,name='phat_insert'),
    path('phat/', views.phat_list,name='phat_list'),
    path('phat/update/<int:id>/', views.phat_form,name='phat_update'), 
    path('phat/delete/<int:id>/',views.phat_delete,name='phat_delete'),
    path('phat/import/xls', importxls.importxls_phat, name='importxls_phat'),
    path('phat/export/xls/<str:contract>', exportxls.exportxls_phat, name='exportxls_phat'),


    path('tienve/insert/', views.tienve_form,name='tienve_insert'),
    path('tienve/', views.tienve_list,name='tienve_list'),
    path('tienve/update/<int:id>/', views.tienve_form,name='tienve_update'), 
    path('tienve/delete/<int:id>/',views.tienve_delete,name='tienve_delete'),
    path('tienve/import/xls', importxls.importxls_tienve, name='importxls_tienve'),
    path('tienve/export/xls/<str:contract>', exportxls.exportxls_tienve, name='exportxls_tienve'),

    path('sales/insert/', views.sales_form,name='sales_insert'),
    path('sales/', views.sales_list,name='offer_list'),
    path('sales/update/<int:id>/', views.sales_form,name='sales_update'), 
    path('sales/delete/<int:id>/',views.sales_delete,name='sales_delete'),
    path('sales/import/xls', importxls.importxls_sales, name='importxls_sales'),
    path('sales/export/xls', exportxls.exportxls_sales, name='exportxls_sales'),

    path('inquiry/insert/', views.inquiry_form,name='inquiry_insert'),
    path('inquiry/', views.inquiry_list,name='inquiry_list'),
    path('inquiry/update/<int:id>/', views.inquiry_form,name='inquiry_update'), 
    path('inquiry/delete/<int:id>/',views.inquiry_delete,name='inquiry_delete'),
    path('inquiry/import/xls', importxls.importxls_inquiry, name='importxls_inquiry'),
    path('inquiry/export/xls', exportxls.exportxls_inquiry, name='exportxls_inquiry'), 

    path('client/insert/', views.client_form,name='client_insert'),
    path('client/', views.client_list,name='client_list'),
    path('client/update/<int:id>/', views.client_form,name='client_update'), 
    path('client/delete/<int:id>/',views.client_delete,name='client_delete'),
    path('client/import/xls', importxls.importxls_client, name='importxls_client'),
    path('client/export/xls', exportxls.exportxls_client, name='exportxls_client'),
   
    path('gcode/insert/', views.gcode_form,name='gcode_insert'),
    path('gcode/', views.gcode_list,name='gcode_list'),
    path('gcode/update/<int:id>/', views.gcode_form,name='gcode_update'), 
    path('gcode/delete/<int:id>/',views.gcode_delete,name='gcode_delete'),
    path('gcode/import/xls', importxls.importxls_gcode, name='importxls_gcode'),
    path('gcode/export/xls', exportxls.exportxls_gcode, name='exportxls_gcode'),
  
    path('supplier/insert/', views.supplier_form,name='supplier_insert'),
    path('supplier/', views.supplier_list,name='supplier_list'),
    path('supplier/update/<int:id>/', views.supplier_form,name='supplier_update'), 
    path('supplier/delete/<int:id>/',views.supplier_delete,name='supplier_delete'),
    path('supplier/import/xls', importxls.importxls_supplier, name='importxls_supplier'),
    path('supplier/export/xls', exportxls.exportxls_supplier, name='exportxls_supplier'),

   
    path('contract/insert/', views.contract_form,name='contract_insert'),
    path('contract/', views.contract_list,name='contract_list'),
    path('contract/update/<int:id>/', views.contract_form,name='contract_update'), 
    path('contract/delete/<int:id>/',views.contract_delete,name='contract_delete'),
    path('contract/import/xls', importxls.importxls_contract, name='importxls_contract'),
    path('contract/export/xls', exportxls.exportxls_contract, name='exportxls_contract'),
    
    path('lydowin/insert/', views.lydowin_form,name='lydowin_insert'),
    path('lydowin/', views.lydowin_list,name='lydowin_list'),
    path('lydowin/update/<int:id>/', views.lydowin_form,name='lydowin_update'), 
    path('lydowin/delete/<int:id>/',views.lydowin_delete,name='lydowin_delete'),
    path('lydowin/import/xls', importxls.importxls_lydowin, name='importxls_lydowin'),
    path('lydowin/export/xls', exportxls.exportxls_lydowin, name='exportxls_lydowin'),
      
    path('lydoout/insert/', views.lydoout_form,name='lydoout_insert'),
    path('lydoout/', views.lydoout_list,name='lydoout_list'),
    path('lydoout/update/<int:id>/', views.lydoout_form,name='lydoout_update'), 
    path('lydoout/delete/<int:id>/',views.lydoout_delete,name='lydoout_delete'),
    path('lydoout/import/xls', importxls.importxls_lydoout, name='importxls_lydoout'),
    path('lydoout/export/xls', exportxls.exportxls_lydoout, name='exportxls_lydoout'),
        
    path('nlnk/insert/', views.nlnk_form,name='nlnk_insert'),
    path('nlnk/',views.nlnk_list,name='nlnk_list'),
    path('nlnk/update/<int:id>/', views.nlnk_form,name='nlnk_update'), 
    path('nlnk/delete/<int:id>/',views.nlnk_delete,name='nlnk_delete'),
    path('nlnk/import/xls', importxls.importxls_nlnk, name='importxls_nlnk'),
    path('nlnk/export/xls/<str:po>', exportxls.exportxls_nlnk, name='exportxls_nlnk'),
    
    path('profit/', views.profit_list,name='profit_list'),
    path('profit/show/<str:contract>', importxls.profit_show,name='profit_show'),
    path('profit/export/xls/<str:contract>', exportxls.exportxls_profit,name='exportxls_profit'),
    path('reportseller/', views.reportseller_list,name='reportseller_list'),
    path('scanorder/', views.scanorder_list,name='scanorder_list'),
    path('scanorder/import/xls', importxls.importxls_scanorder,name='importxls_scanorder'),
    path('scanorder/export/xls/<int:id>', exportxls.exportxls_scanorder,name='exportxls_scanorder'),

    path('', views.home, name='home'),
    path('login/',views.loginpage, name="loginpage"),
    path('logout/',auth_views.LogoutView.as_view(next_page='/'),name='logout'),
]

gcodeproj/gcodeproj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404,handler500

from django.conf.urls import url
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gcodedb.urls')),
    #url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    #url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]
#handler404 = 'gcodedb.views.error404'
#handler500 = 'gcodedb.views.error500'

gcodeproj/gcodedb/views.py
from django import forms
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView,CreateView,FormView
from django.http import HttpResponse,HttpResponseRedirect
from django.forms import ModelForm, formsets, inlineformset_factory,modelformset_factory,formset_factory
from django.views.generic import CreateView, ListView, UpdateView
from .models import Contract, Danhgiagcode, G1code, Nhaplieuban, GDV, Gcode, Inquiry,Client, Nhaplieunhapkhau, Nhaplieumua, Phat, Sales,Supplier,Lydowin,Lydoout, Tienve
from django.db import transaction,IntegrityError
from .forms import DanhgiagcodeForm, GcodeForm, NlbForm, NlnkForm, MyForm, OfferForm, NlmForm, PhatForm, SalesForm, ClientForm, InquiryForm,GDVForm,SupplierForm,ContractForm,LydooutForm,LydowinForm, TienveForm
from .filters import ClientFilter
from django.db.models import Q
from datetime import date
import csv
from django.utils.html import format_html
import pandas as pd
import numpy as np
from django.urls import reverse
from fuzzywuzzy import fuzz,process
from django.contrib.auth.decorators import login_required
from .decorators import allowed_permission
from  django.contrib.auth import authenticate,login
from django.template import Context, loader

""" class PostListView(ListView):
   queryset = Gcode.objects.all().order_by('-ma')
   template_name = 'gcodedb/show.html'
   context_object_name = 'Gcodes'
class PostDetailView(DetailView):
   model = Gcode
   template_name = 'gcodedb/detail.html'
   context_object_name = 'gcodekey'
 """

""" def savedata(request):
    form = GcodeForm()
    if request.method == 'POST':
        form = GcodeForm(request.POST)
        if form.is_valid():
            counter = Gcode.objects.filter(ma=request.POST.get('ma')).count()
            if counter>0:
                gcode = Gcode.objects.get(ma=request.POST.get('ma'))
                gcode.mota = request.POST.get('mota')
                gcode.markupdinhmuc = request.POST.get('markupdinhmuc')
                gcode.save()
            else:
                form.save()
            return HttpResponseRedirect('/')
    return render(request, 'gcodedb/show.html', {'form': form})
def displaydata(request):
    results = Gcode.objects.all()
    return render(request, 'gcodedb/show.html',{'Gcodes':results})

class NestedSearch(FormView):
    form_class = formset_factory(SearchQueryForm)
    template_name = 'gcodedb/searchclient.html'
    success_url = ''

    def form_valid(self, form):
        # Build the query chain
        qs = []
        for form_query in form.cleaned_data:
            q = {'{0}__{1}'.format(form_query['query_field'], form_query['lookup']): form_query['query']}
            qs.append(Q(**q))

        results = Client.objects.filter(*qs)

        return self.render_to_response(self.get_context_data(results=results, form=form))

def create(request):
	context = {}
	InquiryFormSet = modelformset_factory(Inquiry, form=InquiryForm)	
	form = ClientForm(request.POST or None)
	formset = InquiryFormSet(request.POST or None, queryset= Inquiry.objects.none(), prefix='fk_Inquiryclient')
	if request.method == "POST":
		if form.is_valid() and formset.is_valid():
			try:
				with transaction.atomic():
					client = form.save(commit=False)
					client.save()

					for inquiry in formset:
						data = inquiry.save(commit=False)
						data.client = client
						data.save()
			except IntegrityError:
				print("Error Encountered")

			return redirect('gcodedb:list')


	context['formset'] = formset
	context['form'] = form
	return render(request, 'gcodedb/create.html', context)

def list(request):
	datas = Client.objects.all()
	return render(request, 'gcodedb/list.html', {'datas':datas})
def search(request):
    client_list = Client.objects.all()
    client_filter = ClientFilter(request.GET, queryset=client_list)
    return render(request, 'gcodedb/search.html', {'filter': client_filter})
def CreateOffer(request):
    context = {}
    OfferFormSet = modelformset_factory(G1code, form=OfferForm)	
    form = InquiryForm(request.POST or None)
    formset = OfferFormSet(request.POST or None, queryset= G1code.objects.none(), prefix='fk_g1codeinquiry')
    if request.method == "POST":
        if form.is_valid() and formset.is_valid():
            try:
                with transaction.atomic():
                    inquiry = form.save(commit=False)
                    inquiry.save()
                    for offer in formset:
                        data = offer.save(commit=False)
                        data.inquirycode = inquiry
                        data.dateupdate = date.today()
                        data.save()
                        lydowins = offer.cleaned_data.get('lydowincode')
                        for lydoitem in lydowins:
                            data.lydowincode.add(lydoitem)
                            data.save()
                        lydoouts = offer.cleaned_data.get('lydooutcode')
                        for lydoitem in lydoouts:
                            data.lydooutcode.add(lydoitem)
                            data.save()
            except IntegrityError:
                print("Error Encountered")
			#return redirect('gcodedb:CreateOffer')
        else:
            print(form.errors)
            print(formset.errors)
    context['formset'] = formset
    context['form'] = form
    return render(request, 'gcodedb/createoffer.html', context) """

@login_required(login_url='gcodedb:loginpage')
@allowed_permission(allowed_roles={'gcodedb.view_inquiry'})
def inquiry_list(request):
	inquiry_list = Inquiry.objects.all()
	return render(request, 'gcodedb/inquiry_list.html', {'inquiry_list':inquiry_list})

@login_required(login_url='gcodedb:loginpage')
@allowed_permission(allowed_roles={'gcodedb.view_inquiry'})
def inquiry_form(request, id=None):
    if request.method == "GET":
        if id == None:
            form = InquiryForm()
        else:
            inquiry = Inquiry.objects.get(pk=id)
            form = InquiryForm(instance=inquiry)
        return render(request, "gcodedb/inquiry_form.html", {'form': form})
    else:
        if id == None:
            form = InquiryForm(request.POST)
        else:
            inquiry = Inquiry.objects.get(pk=id)
            form = InquiryForm(request.POST,instance= inquiry)
        if form.is_valid():
            form.save()
        return redirect('/inquiry/')


@login_required(login_url='gcodedb:loginpage')
@allowed_permission(allowed_roles={'gcodedb.delete_inquiry'})
def inquiry_delete(request,id):
    inquiry = Inquiry.objects.get(pk=id)
    inquiry.delete()
    return redirect('/inquiry/')

@login_required(login_url='gcodedb:loginpage')
@allowed_permission(allowed_roles={'gcodedb.view_client'})
def client_list(request):
	client_list = Client.objects.all()
	return render(request, 'gcodedb/client_list.html', {'client_list':client_list})

@login_required(login_url='gcodedb:loginpage')
@allowed_permission(allowed_roles={'gcodedb.view_client'})
def client_form(request, id=None):
    if request.method == "GET":
        if id == None:
            form = ClientForm()
        else:
            client = Client.objects.get(pk=id)
            form = ClientForm(instance=client)
        return render(request, "gcodedb/client_form.html", {'form': form})
    else:
        if id == None:
            form = ClientForm(request.POST)
        else:
            client = Client.objects.get(pk=id)
            form = ClientForm(request.POST,instance= client)
        if form.is_valid():
            form.save()
        return redirect('/client/')


@login_required(login_url='gcodedb:loginpage')
@allowed_permission(allowed_roles={'gcodedb.delete_client'})
def client_delete(request,id):
    client = Client.objects.get(pk=id)
    client.delete()
    return redirect('/client/')

@login_required(login_url='gcodedb:loginpage')
@allowed_permission(allowed_roles={'gcodedb.view_gcode'})
def gcode_list(request):
    msg = []
    msgresult = ""
    if request.method == "POST":
        gcode_set = set()
        code_list = Gcode.objects.values_list('ma',flat=True)
        kymahieu_list = Gcode.objects.values_list('kymahieuinq',flat=True)
        description_list = Gcode.objects.values_list('mota',flat=True)
        ratio_code = process.extract(request.POST.get("gcodesearch"),code_list)
        ratio_kymahieu = process.extract(request.POST.get("gcodesearch"),kymahieu_list)
        ratio_des = process.extract(request.POST.get("gcodesearch"),description_list)
        for ratio in ratio_code:
            if ratio[1] >= 90:
                gcode_set.add(Gcode.objects.get(ma = ratio[0]).ma)
        for ratio in ratio_kymahieu:
            if ratio[1] >= 90:
                gcode_set.add(Gcode.objects.get(kymahieuinq = ratio[0]).ma)
        for ratio in ratio_des:
            if ratio[1] >= 90:
                gcode_set.add(Gcode.objects.get(mota = ratio[0]).ma)
        df = pd.DataFrame(columns=['Gcode','Ký mã hiệu','Mô tả']) 
        if len(gcode_set)>0:
            for item in gcode_set:
                gcode = Gcode.objects.get(ma=item)
                df = df.append(pd.DataFrame({'Gcode':[gcode.ma],
                                            'Ký mã hiệu':[gcode.kymahieuinq],
                                            'Mô tả':[gcode.mota]}))
            msgresult = format_html("Have <b>{}</b> results for your search query as the below:<br>",len(gcode_set))
            html = df.to_html(index=False,justify='center')
            context = {'gcode_list': html,'msgresult':msgresult}
            return render(request, 'gcodedb/gcode_list.html', context)
        else: 
            msgresult = format_html("No results could be found for your search query")
    return render(request, 'gcodedb/gcode_list.html', {'msgresult':msgresult})


@login_required(login_url='gcodedb:loginpage')
@allowed_permission(allowed_roles={'gcodedb.view_gcode'})                        
def gcode_form(request, id=None):
    if request.method == "GET":

gcodeproj/gcodedb/templates/gcodedb/inquiry_list.html
{% extends "base.html" %}
{% block content %}

<table class="table table-borderless">
    <form method="POST" action="{% url 'gcodedb:importxls_inquiry' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="myfile" accept=".xls,.xlsx">
        <button type="submit">Import Excel</button>
    </form>
    <br>
    <a href="{% url 'gcodedb:exportxls_inquiry' %}">Export to Excel</a>
    <thead class="border-bottom font-weight-bold">
        <tr>
            <td>Inquiry</td>
            <td>Date submit</td>
            <td>Client</td>
            <td>
                <a href="/inquiry/insert" class="btn btn-outline-success">
                    <i class="fas fa-plus"></i> Add New
                </a>
            </td>
        </tr>
    </thead>
    <tbody>
        {% for inquiry in inquiry_list %}
            <tr>
                <td>{{inquiry.inquirycode}}</td>
                <td>{{inquiry.datesubmitbid|date:"d-m-Y"}}</td>
                <td>{{inquiry.client}}</td>
                <td>
                    <a href="/inquiry/update/{{inquiry.id}}" class="btn text-secondary px-0">
                        <i class="far fa-edit fa-lg"></i>
                    </a>
                    <a href="/inquiry/delete/{{inquiry.id}}" class="btn text-secondary px-0">
                        <i class="far fa-trash-alt fa-lg text-danger float-right"></i>
                    </a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}

gcodeproj/gcodedb/templates/gcodedb/lydoout_list.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<table class="table table-borderless">
    <form method="POST" action="{% url 'gcodedb:importxls_lydoout' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="myfile" accept=".xls">
        <button type="submit">Import Excel</button>
    </form>
    <br>
    <a href="{% url 'gcodedb:exportxls_lydoout' %}">Export to Excel</a>
    <thead class="border-bottom font-weight-bold">
        <tr>
            <td>Lý do out</td>
            <td>Mô tả</td>
            <td>
                <a href="/lydoout/insert" class="btn btn-outline-success">
                    <i class="fas fa-plus"></i> Add New
                </a>
            </td>
        </tr>
    </thead>
    <tbody>
        {% for lydoout in lydoout_list %}
            <tr>
                <td>{{lydoout.lydooutcode}}</td>
                <td><textarea id="autosize" cols="30" rows="1">{{lydoout.detail}}</textarea></td>
                <td>
                    <a href="/lydoout/update/{{lydoout.id}}" class="btn text-secondary px-0">
                        <i class="far fa-edit fa-lg"></i>
                    </a>
                    <a href="/lydoout/delete/{{lydoout.id}}" class="btn text-secondary px-0">
                        <i class="far fa-trash-alt fa-lg text-danger float-right"></i>
                    </a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}

{% block extra_script %}
<script src="{% static 'js/autosize.min.js' %}"></script>
<script>autosize(document.querySelectorAll('#autosize'));</script>
{% endblock%}

gcodeproj/gcodedb/templates/gcodedb/lydowin_list.html
{% extends "base.html" %}
{% block css %}

{% endblock %}
{% block content %}
{% load static %}
<table class="table table-borderless">
    <form method="POST" action="{% url 'gcodedb:importxls_lydowin' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="myfile" accept=".xls">
        <button type="submit">Import Excel</button>
    </form>
    <br>
    <a href="{% url 'gcodedb:exportxls_lydowin' %}">Export to Excel</a>
    <thead class="border-bottom font-weight-bold">
        <tr>
            <td>Lý do win</td>
            <td>Mô tả</td>
            <td>
                <a href="/lydowin/insert" class="btn btn-outline-success">
                    <i class="fas fa-plus"></i> Add New
                </a>
            </td>
        </tr>
    </thead>
    <tbody>
        {% for lydowin in lydowin_list %}
            <tr>
                <td>{{lydowin.lydowincode}}</td>
                <td><textarea id="autosize" cols="30" rows="1">{{lydowin.detail}}</textarea></td>
                <td>
                    <a href="/lydowin/update/{{lydowin.id}}" class="btn text-secondary px-0">
                        <i class="far fa-edit fa-lg"></i>
                    </a>
                    <a href="/lydowin/delete/{{lydowin.id}}" class="btn text-secondary px-0">
                        <i class="far fa-trash-alt fa-lg text-danger float-right"></i>
                    </a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{{ myform.media }}
{{ myform }}
{% endblock content %}

{% block extra_script %}
<script src="{% static 'js/autosize.min.js' %}"></script>
<script>autosize(document.querySelectorAll('#autosize'));</script>
{% endblock%}

gcodeproj/gcodedb/templates/gcodedb/nlb_list.html
{% extends "base.html" %}
{% block content %}
<a href="{% url 'gcodedb:exportxls_nlb' %}">Export Form to Excel</a>
<form method="POST" action="{% url 'gcodedb:importxls_nlb' %}" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="myfile" accept=".xls,.xlsx">
    <button type="submit">Import Excel</button>
</form>
<br>
<br>
{{ nlb_list|safe }}
<br>
{% if messages_ %}
    <ul class="messagelist">
        {% for message in messages_ %}
            <li>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

{% if warnings %}
<br>
<p>Some warnings:</p>
    <ul class="messagelist">
        {% for warn in warnings %}
            <li>{{ warn }}</li>
        {% endfor %}
    </ul>
{% endif %}
{% endblock content %}

gcodeproj/gcodedb/templates/gcodedb/supplier_list.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<table class="table table-borderless">
    <form method="POST" action="{% url 'gcodedb:importxls_supplier' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="myfile" accept=".xls">
        <button type="submit">Import Excel</button>
    </form>
    <br>
    <a href="{% url 'gcodedb:exportxls_supplier' %}">Export to Excel</a>
    <thead class="border-bottom font-weight-bold">
        <tr>
            <td>Supplier</td>
            <td>Full Name</td>
            <td>Duyệt PO (Max)</td>
            <td>
                <a href="/supplier/insert" class="btn btn-outline-success">
                    <i class="fas fa-plus"></i> Add New
                </a>
            </td>
        </tr>
    </thead>
    <tbody>
        {% for supplier in supplier_list %}
            <tr>
                <td>{{supplier.suppliercode}}</td>
                <td>{{supplier.fullname}}</td>
                <td><input class='currency' value="{{supplier.duyetpomax}}"></td>
                <td>
                    <a href="/supplier/update/{{supplier.id}}" class="btn text-secondary px-0">
                        <i class="far fa-edit fa-lg"></i>
                    </a>
                    <a href="/supplier/delete/{{supplier.id}}" class="btn text-secondary px-0">
                        <i class="far fa-trash-alt fa-lg text-danger float-right"></i>
                    </a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}

{% block extra_script %}
<script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<script type="text/javascript">
/*     var currencyInput = document.querySelector('input[type="currency"]') */
    var currency = 'VND' 
    // format inital value
    onBlur({target:currencyInput})
    // bind event listeners
    setInterval(function() {
    $('input.currency').each(function(){
        onFocus($(this));
        onBlur($(this));
    });

    }, 2000);
    function localStringToNumber( s ){
        return Number(String(s).replace(/[^0-9.-]+/g,""))
    }
    function onFocus(e){
        var value = e.target.value;
        e.target.value = value ? localStringToNumber(value) : ''
    }
    function onBlur(e){
        var value = e.target.value
        var options = {
            maximumFractionDigits : 2,
            currency              : currency,
            style                 : "currency",
            currencyDisplay       : "symbol"
        }
        e.target.value = value 
            ? localStringToNumber(value).toLocaleString(undefined, options)
            : ''
    }
</script>
{% endblock%}

gcodeproj/gcodedb/templates/gcodedb/tienve_list.html
{% extends "base.html" %}
{% block content %}
<form method="POST" action="{% url 'gcodedb:tienve_list'%}">
    {% csrf_token %}
    <label for="contractsearch">Nhập Contract No.:</label>
    <input type="text" id="contractsearch" name="contractsearch"><br>
    <button type="submit">Search PO</button>
</form>
<br>
{{msgresult}}
{% if msg %}
    <ul class="messagelist">
        {% for message in msg %}
            <li>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
<br>
<br>
<form method="POST" action="{% url 'gcodedb:importxls_tienve' %}" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="myfile" accept=".xls,.xlsx">
    <button type="submit">Import Excel</button>
</form>
<br>
<br>
{{ tienve_list|safe }}
<br>
{% if messages_ %}
    <ul class="messagelist">
        {% for message in messages_ %}
            <li>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

{% if warnings %}
<br>
<p>Some warnings:</p>
    <ul class="messagelist">
        {% for warn in warnings %}
            <li>{{ warn }}</li>
        {% endfor %}
    </ul>
{% endif %}
{% endblock content %}